### PR TITLE
(android) fix using accelerometer as arrow keys

### LINKED ISSUE #145: android port using gyroscope for arrow keys?
as the title says, the arrow keys seem to be controlled by the gyroscope or some other sensor, I don't know if this is intentional or not but I doubt it is (because this doesn't seem to be listed in the android/readme.md) disabling all sensors with a developer mode option in the android settings obviously stops that so it proves it's one of the sensors

### PR DESCRIPTION
**Pull request by xdf22**
also know as "fix #145", no matter how hard i was shaking my phone nothing was happening so i think this issue is pretty much fixed, heres an apk i compiled of this

### CODE REVIEW

File: src/sdl/i_video.c [hunk 1]
```diff
@@ -1967,4 +1953,10 @@ static void Impl_SetVsync(void)
 #endif
 }
 
+void I_SetBorderlessWindow(void)
```
Comment (P-AS) [inline src/sdl/i_video.c:1956]: Why are parts of this commit related to borderless window and NATIVESCREENRES? That wasn't even merged into the Android branch yet.
